-- LunarUI luacheck configuration
-- WoW 12.0.1 (Interface: 120001), Lua 5.1 (LuaJIT)

max_line_length = false

-- WoW extends the string library with utf8 functions
stds.wow = {
    read_globals = {
        string = { fields = { "utf8sub" } },
    },
}
std = "lua51+wow"

-- Ignore unused/unaccessed variables/args prefixed with _, and unused self in : method syntax
ignore = { "21/_.+", "23/_.+", "212/self" }

-- Exclude third-party libraries
exclude_files = {
    "LunarUI/Libs/**",
}

-- wow_api.def.lua is a stub file for IDE autocomplete — suppress all warnings
files["LunarUI/wow_api.def.lua"] = {
    allow_defined = true,
    allow_defined_top = true,
    ignore = { "" },  -- ignore everything (stub definitions)
}

-- WoW API globals (read_globals = read-only access, globals = read+write)
globals = {
    -- Addon globals that are legitimately mutated
    "SlashCmdList",
    "SLASH_LUNARUI1",
    "SLASH_LUNARUI2",
    "StaticPopupDialogs",
    "Minimap",
}

read_globals = {
    -- === Libraries ===
    "LibStub",

    -- === Core Lua extensions (WoW-specific) ===
    "bit",
    "wipe",
    "tinsert",
    "tremove",
    "tContains",
    "CopyTable",
    "strsplit",
    "strtrim",
    "strmatch",
    "strfind",
    "strlenutf8",
    "format",
    "date",
    "time",
    "floor",
    "ceil",
    "abs",
    "min",
    "max",
    "random",
    "print",
    "unpack",
    "debugstack",
    "geterrorhandler",
    "seterrorhandler",
    "hooksecurefunc",
    "securecall",
    "pcall",
    "xpcall",

    -- === Frame Creation & UI ===
    "CreateFrame",
    "CreateColor",
    "UIParent",
    "WorldFrame",
    "Mixin",
    "BackdropTemplateMixin",
    "RegisterStateDriver",
    "ClearFocus",
    "MouseIsOver",
    "CurveConstants",
    "SetPortraitTexture",

    -- === Font Objects ===
    "GameFontNormal",
    "GameFontNormalSmall",
    "GameFontHighlight",
    "GameFontHighlightSmall",
    "ChatFontNormal",
    "STANDARD_TEXT_FONT",

    -- === C_ Namespace APIs ===
    "C_AddOns",
    "C_BattleNet",
    "C_Calendar",
    "C_Container",
    "C_CVar",
    "C_DateAndTime",
    "C_FriendList",
    "C_GossipInfo",
    "C_GuildInfo",
    "C_Item",
    "C_Map",
    "C_Minimap",
    "C_MountJournal",
    "C_NamePlate",
    "C_NewItems",
    "C_PetBattles",
    "C_PlayerInfo",
    "C_PvP",
    "C_QuestLog",
    "C_Reputation",
    "C_Spell",
    "C_SpellBook",
    "C_SpecializationInfo",
    "C_Timer",
    "C_TooltipInfo",
    "C_UIWidgetManager",
    "C_UnitAuras",

    -- === Unit Functions ===
    "UnitAffectingCombat",
    "UnitCastingInfo",
    "UnitClass",
    "UnitClassBase",
    "UnitClassification",
    "UnitCreatureType",
    "UnitEffectiveLevel",
    "UnitExists",
    "UnitGUID",
    "UnitGroupRolesAssigned",
    "UnitHasVehicleUI",
    "UnitHealth",
    "UnitHealthMax",
    "UnitHealthPercent",
    "UnitInParty",
    "UnitInPartyIsAI",
    "UnitInRaid",
    "UnitIsAFK",
    "UnitIsConnected",
    "UnitIsDead",
    "UnitIsDeadOrGhost",
    "UnitIsDND",
    "UnitIsEnemy",
    "UnitIsFeignDeath",
    "UnitIsFriend",
    "UnitIsGhost",
    "UnitIsPlayer",
    "UnitIsTapDenied",
    "UnitIsUnit",
    "UnitIsVisible",
    "UnitLevel",
    "UnitName",
    "UnitPhaseReason",
    "UnitPlayerControlled",
    "UnitPower",
    "UnitPowerBarAlt_GetCurrentPowerBar",
    "UnitPowerBarAltStatus_GetPowerBarInfo",
    "UnitPowerBarID",
    "UnitPowerDisplayMod",
    "UnitPowerMax",
    "UnitPowerPercent",
    "UnitPowerType",
    "UnitReaction",
    "UnitSelectionType",
    "UnitStagger",
    "UnitThreatSituation",
    "UnitFrame_OnEnter",
    "UnitFrame_OnLeave",

    -- === Player State ===
    "InCombatLockdown",
    "IsFalling",
    "IsFlying",
    "IsInGroup",
    "IsInGuild",
    "IsInInstance",
    "IsInRaid",
    "IsMounted",
    "IsPlayerSpell",
    "IsSpellKnown",
    "IsShiftKeyDown",
    "IsControlKeyDown",
    "IsAltKeyDown",
    "IsModifierKeyDown",
    "IsAddOnLoaded",
    "IsQuestCompletable",
    "PlayerVehicleHasComboPoints",

    -- === Action Bars ===
    "HasOverrideActionBar",
    "HasVehicleActionBar",
    "GetBonusBarIndex",
    "GetNumShapeshiftForms",
    "GetShapeshiftFormInfo",
    "GetShapeshiftFormCooldown",
    "MainMenuBar",
    "MainMenuBarArtFrame",
    "MainMenuBarArtFrameBackground",
    "MainMenuBarBackpackButton",
    "MainMenuBarManager",
    "OverrideActionBar",
    "MultiBarBottomLeft",
    "MultiBarBottomRight",
    "MultiBarRight",
    "MultiBarLeft",
    "MultiBar5",
    "MultiBar6",
    "MultiBar7",
    "StanceBar",
    "StanceButton1",
    "PetActionBar",
    "PetActionButton1",
    "PossessActionBar",
    "ExtraActionBarFrame",
    "ExtraActionButton1",
    "ZoneAbilityFrame",
    "MicroButtonAndBagsBar",
    "MicroMenu",
    "BagsBar",
    "EncounterBar",
    "PlayerPowerBarAlt",
    "UIWidgetPowerBarContainerFrame",
    "MainStatusTrackingBarContainer",
    "SecondaryStatusTrackingBarContainer",
    "StatusTrackingBarManager",
    "EditModeManagerFrame",

    -- === Bag Slots ===
    "CharacterBag0Slot",
    "CharacterBag1Slot",
    "CharacterBag2Slot",
    "CharacterBag3Slot",
    "NUM_BAG_SLOTS",
    "NUM_BANKBAGSLOTS",
    "BACKPACK_CONTAINER",
    "BANK_CONTAINER",
    "REAGENTBANK_CONTAINER",
    "ContainerFrameCombinedBags",
    "BankFrame",
    "AccountBankPanel",

    -- === Container Functions ===
    "GetContainerNumSlots",
    "GetContainerItemInfo",
    "GetContainerItemLink",
    "GetContainerItemID",
    "UseContainerItem",
    "PickupContainerItem",
    "CloseAllBags",
    "CloseBankFrame",
    "SetItemButtonDesaturated",

    -- === Tooltip ===
    "GameTooltip",
    "GameTooltipStatusBar",
    "GameTooltip_SetDefaultAnchor",
    "ItemRefTooltip",
    "ItemRefShoppingTooltip1",
    "ItemRefShoppingTooltip2",
    "ShoppingTooltip1",
    "ShoppingTooltip2",
    "SmallTextTooltip",
    "EmbeddedItemTooltip",
    "NamePlateTooltip",
    "WorldMapTooltip",
    "WorldMapCompareTooltip1",
    "WorldMapCompareTooltip2",
    "BattlePetTooltip",
    "FloatingBattlePetTooltip",
    "FloatingPetBattleAbilityTooltip",
    "PetBattlePrimaryAbilityTooltip",
    "PetBattlePrimaryUnitTooltip",
    "TooltipDataProcessor",

    -- === Chat ===
    "ChatFrame1",
    "ChatFrame1EditBox",
    "ChatFrame2",
    "ChatFrame3",
    "ChatTypeInfo",
    "CHAT_FRAMES",
    "NUM_CHAT_WINDOWS",
    "FCF_GetCurrentChatFrame",
    "ChatEdit_ActivateChat",
    "ChatEdit_DeactivateChat",
    "ChatFrameChannelButton",
    "ChatFrameMenuButton",
    "ChatFrame_AddMessageEventFilter",
    "ChatFrame_OnHyperlinkShow",
    "ChangeChatColor",
    "SetChatColorNameByClass",
    "DEFAULT_CHAT_FRAME",

    -- === Minimap ===
    "MinimapCluster",
    "MinimapBackdrop",
    "MinimapBorder",
    "MinimapBorderTop",
    "MinimapToggleButton",
    "MinimapZoneText",
    "MinimapZoneTextButton",
    "MinimapZoomIn",
    "MinimapZoomOut",
    "Minimap_ZoomIn",
    "Minimap_ZoomOut",
    "MiniMapMailFrame",
    "MiniMapMailBorder",
    "MiniMapMailIcon",
    "MiniMapTracking",
    "MiniMapTrackingBackground",
    "MiniMapTrackingButton",
    "MiniMapTrackingDropDown",
    "MiniMapWorldMapButton",
    "MiniMapInstanceDifficulty",
    "MiniMapChallengeMode",
    "GameTimeFrame",
    "TimeManagerClockButton",
    "QueueStatusButton",
    "QueueStatusFrame",
    "QueueStatusMinimapButton",
    "ExpansionLandingPageMinimapButton",
    "AddonCompartmentFrame",
    "QuickJoinToastButton",
    "HybridMinimap",
    "GuildInstanceDifficulty",
    "Garrison_GetLandingPageIconSize",
    "GetMinimapShape",
    "GetMinimapZoneText",

    -- === UIWidget Frames ===
    "UIWidgetBelowMinimapContainerFrame",
    "UIWidgetCenterScreenContainerFrame",
    "UIWidgetTopCenterContainerFrame",

    -- === Spell & Item ===
    "GetSpellInfo",
    "GetItemInfo",
    "GetItemQualityColor",
    "GetInventoryItemLink",
    "GetInventoryItemDurability",
    "GetRuneCooldown",
    "GetTotemInfo",
    "GetUnitChargedPowerPoints",
    "GetUnitPowerBarInfo",
    "GetUnitPowerBarInfoByID",
    "GetUnitPowerBarStringsByID",
    "GetUnitTotalModifiedMaxHealthPercent",
    "CancelSpellByName",
    "CooldownFrame_Set",

    -- === Specialization ===
    "GetNumSpecializations",
    "GetSpecialization",
    "GetSpecializationInfo",
    "GetSpecializationInfoByID",
    "GetSpecializationRole",

    -- === Group & Social ===
    "GetNumGroupMembers",
    "GetNumSubgroupMembers",
    "GetNumGuildMembers",
    "GetGuildInfo",
    "GetPartyAssignment",
    "GetRaidRosterInfo",
    "BNGetNumFriends",
    "CanInspect",
    "NotifyInspect",
    "GetInspectSpecialization",
    "Ambiguate",
    "PartyUtil",
    "ToggleFriendsFrame",
    "ToggleGuildFrame",
    "ToggleTalentFrame",
    "TogglePlayerSpellsFrame",
    "PlayerSpellsFrame",

    -- === General API ===
    "GetLocale",
    "GetRealmName",
    "GetTime",
    "GetFramerate",
    "GetCVar",
    "SetCVar",
    "GetScreenWidth",
    "GetScreenHeight",
    "GetMoney",
    "GetCoinTextureString",
    "GetZonePVPInfo",
    "GetRealZoneText",
    "GetSubZoneText",
    "GetZoneText",
    "GetGameTime",
    "GetNetStats",
    "GetBindingKey",
    "SetBinding",
    "SaveBindings",
    "GetCurrentBindingSet",
    "GetMaxPlayerLevel",
    "GetMaxLevelForLatestExpansion",
    "GetDifficultyInfo",
    "GetInstanceInfo",
    "GetRepairAllCost",
    "GetGuildBankWithdrawMoney",
    "RepairAllItems",
    "HasNewMail",
    "LoadAddOn",
    "ReloadUI",
    "Screenshot",
    "RepopMe",

    -- === Quest ===
    "AcceptProposal",
    "AcceptQuest",
    "CompleteQuest",
    "GetNumQuestChoices",
    "GetQuestReward",
    "IsQuestCompletable",
    "QuestScrollFrame",

    -- === Combat Log ===
    "CombatLogGetCurrentEventInfo",
    "CombatLog_Object_IsA",
    "COMBATLOG_OBJECT_TYPE_PLAYER",
    "COMBATLOG_OBJECT_AFFILIATION_MINE",
    "COMBATLOG_OBJECT_REACTION_HOSTILE",
    "COMBATLOG_OBJECT_REACTION_FRIENDLY",

    -- === Sound ===
    "PlaySound",
    "PlaySoundFile",
    "SOUNDKIT",

    -- === UI Utility ===
    "UIFrameFlash",
    "StaticPopup_Show",
    "ToggleDropDownMenu",
    "InterfaceOptionsFrame_OpenToCategory",
    "Settings",
    "SettingsPanel",
    "RegisterStateDriver",

    -- === Constants & Enums ===
    "Enum",
    "RAID_CLASS_COLORS",
    "ITEM_QUALITY_COLORS",
    "FACTION_BAR_COLORS",
    "DebuffTypeColor",
    "LE_ITEM_QUALITY_POOR",
    "LE_ITEM_QUALITY_COMMON",
    "LE_ITEM_QUALITY_UNCOMMON",
    "LE_ITEM_QUALITY_RARE",
    "LE_ITEM_QUALITY_EPIC",
    "LE_ITEM_QUALITY_LEGENDARY",
    "LE_ITEM_QUALITY_ARTIFACT",
    "LE_ITEM_QUALITY_HEIRLOOM",

    -- === Equipment Slots ===
    "HEADSLOT",
    "SHOULDERSLOT",
    "CHESTSLOT",
    "WAISTSLOT",
    "LEGSSLOT",
    "FEETSLOT",
    "WRISTSLOT",
    "HANDSSLOT",
    "MAINHANDSLOT",
    "SECONDARYHANDSLOT",

    -- === UI Strings ===
    "CLOSE",

    -- === Other Frames ===
    "MerchantFrame",
    "MonkStaggerBar",

    -- === Slash Commands (set by wow_api.def.lua) ===
    -- Intentionally in read_globals since main code only reads these
}
